/*CREATE TABLE `feedback_recipients` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'УИД получателя',
  `recipient` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Получатель',
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'E-mail',
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Описание',
  `created_at` datetime DEFAULT current_timestamp() COMMENT 'Дата создания строки',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Время обновления строки',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Получатели обратной связи';*/

DESCRIBE feedbacks;
-- 
-- Заполняем данными таблицу "Покупатели (клиенты)".
-- 
-- 
-- Обновить инфорамацмю в таблице "Покупатели (клиенты)", после вставки данных.
-- 
-- 
-- Обновляем дату создания записи
UPDATE feedback_recipients SET created_at=DATE_FORMAT(created_at,'2020-%m-%d %T');
-- 

DELETE FROM feedback_recipients WHERE id > 12;

UPDATE feedback_recipients SET recipient='Написать руководству федеральной книжной сети', description='Оставьте отзывы и пожелания по работе интернет-магазина. Ваше мнение важно для нас.' WHERE id=1;
UPDATE feedback_recipients SET recipient='Написать руководству федеральной книжной сети', description='Поделитесь впечатлением о качестве обслуживания в магазине. Мы всегда готовы совершенствоваться.' WHERE id=2;
UPDATE feedback_recipients SET recipient='Задать вопрос по бонусной программе', description='Задайте вопросы по Карте Любимого Покупателя и подарочным картам. Используйте ваши преимущества в полной мере.' WHERE id=3;
UPDATE feedback_recipients SET recipient='Предложить сотрудничество', description='Представьте нам будущие бестселлеры. Рассмотрим интересные предложения от издательств.' WHERE id=4;
UPDATE feedback_recipients SET recipient='Предложить сотрудничество', description='Предложите нам новые товары для хобби и творчества. Наши покупатели любят все, что делает их жизнь интереснее.' WHERE id=5;
UPDATE feedback_recipients SET recipient='Предложить сотрудничество', description='Познакомьте нас с новинками и трендами рынка канцтоваров. В наших магазинах хорошо продаются не только книги.' WHERE id=6;
UPDATE feedback_recipients SET recipient='Предложить сотрудничество', description='Порадуйте нас лучшими образцами своей сувенирной продукции. Наши покупатели ищут яркие подарки для себя и друзей.' WHERE id=7;
UPDATE feedback_recipients SET recipient='Предложить сотрудничество', description='Получите комментарий для публикации в СМИ. Пригласите нас к участию в грандиозных PR-проектах. Мы открыты для сотрудничества.' WHERE id=8;
UPDATE feedback_recipients SET recipient='Предложить сотрудничество', description='Предложите нам новые технологии в области рекламы. Мы приветствуем современные решения и профессионалов своего дела.' WHERE id=9;
UPDATE feedback_recipients SET recipient='Предложить сотрудничество', description='Отправьте нам предложение по аренде торговых площадей. Мы откроем у вас книжный европейского уровня.' WHERE id=10;
UPDATE feedback_recipients SET recipient='Предложить сотрудничество', description='Расскажите нам о своих товарах и производстве. Мы найдем им новое применение и реализуем классные идеи.' WHERE id=11;
UPDATE feedback_recipients SET recipient='Предложить сотрудничество', description='Обращайтесь по всем остальным вопросам, для которых нет специального раздела. Найдем решение вместе.' WHERE id=12;

SELECT * FROM feedback_recipients;

INSERT INTO feedback_recipients (`id`, `recipient`, `email`, `description`, `created_at`, `updated_at`) VALUES
  (1, 'Написать руководству федеральной книжной сети', 'bette85@example.com', 'Оставьте отзывы и пожелания по работе интернет-магазина. Ваше мнение важно для нас.
', '1981-09-19 23:01:57', '2016-05-22 18:39:56')
, (2, 'Написать руководству федеральной книжной сети', 'hane.abagail@example.com', 'Поделитесь впечатлением о качестве обслуживания в магазине. Мы всегда готовы совершенствоваться.', '1976-01-13 10:49:34', '1973-07-09 18:58:53')
, (3, 'Задать вопрос по бонусной программе', 'idavis@example.net', 'Задайте вопросы по Карте Любимого Покупателя и подарочным картам. Используйте ваши преимущества в полной мере.', '1987-05-21 02:34:51', '1989-01-20 15:12:19')
, (4, 'Предложить сотрудничество', 'Представьте нам будущие бестселлеры. Рассмотрим интересные предложения от издательств.', '1980-12-06 13:19:46', '1992-03-26 21:01:42')
, (5, 'Предложить сотрудничество', 'Предложите нам новые товары для хобби и творчества. Наши покупатели любят все, что делает их жизнь интереснее.', '2006-07-01 05:49:57', '1989-03-08 06:35:32')
, (6, 'Предложить сотрудничество', 'Познакомьте нас с новинками и трендами рынка канцтоваров. В наших магазинах хорошо продаются не только книги.', '1989-12-16 05:49:44', '2018-07-25 09:48:11')
, (7, 'Предложить сотрудничество', 'dorris.schulist@example.com', 'Порадуйте нас лучшими образцами своей сувенирной продукции. Наши покупатели ищут яркие подарки для себя и друзей.', '2001-03-10 00:10:40', '1997-04-21 17:43:55')
, (8, 'Предложить сотрудничество', 'jaquelin86@example.org', 'Получите комментарий для публикации в СМИ. Пригласите нас к участию в грандиозных PR-проектах. Мы открыты для сотрудничества.', '1987-12-05 19:31:53', '2013-07-24 07:40:53')
, (9, 'Предложить сотрудничество', 'clemmie64@example.org', 'Предложите нам новые технологии в области рекламы. Мы приветствуем современные решения и профессионалов своего дела.', '1974-01-27 21:53:32', '1973-12-10 06:05:04')
, (10, 'Предложить сотрудничество', 'boyer.frieda@example.com', 'Отправьте нам предложение по аренде торговых площадей. Мы откроем у вас книжный европейского уровня.', '1975-01-15 08:55:59', '2003-02-04 01:07:17'),
, (11, 'Предложить сотрудничество', 'alysa.kshlerin@example.com', 'Расскажите нам о своих товарах и производстве. Мы найдем им новое применение и реализуем классные идеи.', '2020-02-19 21:01:09', '2008-01-28 08:36:30'),
, (12, 'Предложить сотрудничество', 'ada.yost@example.com', 'Обращайтесь по всем остальным вопросам, для которых нет специального раздела. Найдем решение вместе.', '1976-10-27 12:53:29', '1984-09-26 23:48:50'),
, (13, 'Nulla dolorum quibusdam cumque exercitationem animi magnam vel.', 'schuppe.liliana@example.org', 'Dolorem placeat saepe praesentium omnis amet. Nemo temporibus itaque quo veritatis odit quasi. Enim sed impedit nihil quia. Quod odit architecto tenetur voluptates qui.', '2020-07-20 01:21:13', '1975-09-17 06:54:08')
, (14, 'Esse quia tempore dolores.', 'amani.padberg@example.com', 'Harum porro eos velit distinctio. Consequatur nemo debitis similique similique magni. Voluptatum sit deleniti beatae recusandae omnis minus.', '2018-07-04 06:47:16', '1999-01-31 12:07:24')
, (15, 'Et illum illo culpa aut minima recusandae quae.', 'thompson.joanne@example.net', 'Quia reprehenderit aut aut praesentium omnis voluptatem natus. Autem similique tenetur voluptatem autem molestiae est officiis. Quidem quos eos accusamus eum officiis quia. Eos distinctio reiciendis dolor.', '1982-07-18 13:02:27', '1999-08-21 13:20:47')
, (16, 'Molestias minus omnis sunt voluptatibus.', 'jhoeger@example.org', 'Sed nisi laborum ut officia deleniti assumenda incidunt ad. Est laboriosam et neque quam et expedita. Perferendis labore velit aut a. Sed repellat eum deleniti sit sit.', '1982-03-09 22:57:37', '1993-09-03 00:00:49')
, (17, 'Ut et unde iste ex consectetur.', 'jannie47@example.net', 'Ab architecto officiis saepe optio tenetur facere est natus. Dolorum eveniet est nobis necessitatibus ratione unde mollitia ea. Deserunt quam deserunt et ratione rerum labore. Autem enim enim adipisci eos et.', '1985-08-24 01:17:21', '2006-03-14 22:26:16')
, (18, 'Sed laboriosam voluptatem cupiditate inventore.', 'fkirlin@example.org', 'Quos eum neque reiciendis aperiam non totam autem. Consequatur repellendus odio doloribus quaerat nulla aut. Inventore modi et nobis molestiae accusamus ut.', '2001-03-04 04:18:27', '1970-08-06 06:36:50')
, (19, 'Assumenda et officiis rerum laborum.', 'treva89@example.org', 'Impedit est voluptas impedit alias ipsum. Iusto quidem omnis quia sunt aut. Voluptatum quis dolorem ut accusantium aspernatur reiciendis laudantium. Id dicta et qui et officiis qui tenetur.', '1974-02-26 07:02:22', '1977-06-18 21:55:36')
, (20, 'Sit et nesciunt exercitationem impedit consequatur dignissimos.', 'mcdermott.tyrique@example.org', 'Quia nihil adipisci dolores libero ut doloribus. Vel temporibus aut repellendus saepe ut maxime. Nobis minus laboriosam vel ut placeat corporis nihil optio.', '2004-01-28 15:26:52', '2003-03-30 01:09:06')
, (21, 'Quidem nam ducimus aut nobis sapiente eum.', 'delia.vandervort@example.com', 'Quibusdam eius dolorem voluptatem cumque vero. Voluptatem similique corrupti sed omnis ipsum illo nobis officia. Quo vel quis et et expedita. Non inventore qui sapiente ratione blanditiis dolor ipsam. Et et et ratione et tempore et minus.', '2013-08-15 05:05:05', '1987-12-21 05:28:37')
, (22, 'Aliquid sit id nesciunt rerum est deleniti tenetur.', 'schuster.anna@example.net', 'Facilis tempore dolores repellendus vel. Tempore maxime ullam voluptas aliquam maxime sunt. Impedit repellat laboriosam minus.', '1972-02-25 03:22:00', '2009-09-07 04:04:16')
, (23, 'Doloremque perferendis tenetur esse facere sunt quia quis quia.', 'joelle31@example.net', 'Est eos ullam esse iusto cum aut quam. Sed doloribus laborum maiores ut odio. Enim voluptatem aperiam veniam.', '2018-06-24 15:29:29', '1988-03-18 05:23:30')
, (24, 'Et mollitia quidem sit deleniti quis reprehenderit dolorem.', 'bhirthe@example.org', 'Rerum quia maiores animi non. Eveniet et sit aut architecto. Est iure illum molestiae deleniti. Aliquid veniam numquam debitis ex enim nesciunt ipsam.', '1997-05-23 19:26:21', '2006-10-04 07:34:23')
, (25, 'Eos minus quas eaque qui.', 'gilberto63@example.com', 'Neque corrupti nobis aperiam quaerat distinctio quaerat nisi. Quos necessitatibus voluptatibus aut ut soluta est sit. Quod suscipit aut expedita sequi. Accusantium maiores cum sunt et nulla tenetur.', '1999-05-12 04:26:45', '2020-09-11 01:27:04')
, (26, 'Molestias dolore eum incidunt eius libero.', 'zoey.hilpert@example.net', 'Impedit eum aut et. Omnis dolores quaerat esse voluptate distinctio eligendi. Vel modi fugiat ut molestiae.', '1994-11-25 19:37:13', '2020-07-11 19:48:15')
, (27, 'Odio nulla voluptatem repellendus ducimus voluptate a.', 'gwisozk@example.net', 'Accusamus ex aut sit perspiciatis. Ut beatae temporibus earum libero et non velit minima. Veritatis dolorem in dolorum nulla id voluptas possimus.', '2017-04-05 13:31:38', '1974-12-16 16:20:19')
, (28, 'Consequatur officiis sunt eum autem.', 'zstrosin@example.net', 'Qui nesciunt dolores eaque. Omnis neque sint laudantium. Quis blanditiis veniam quibusdam aut sunt quos.', '1994-02-01 23:02:14', '1990-02-05 11:19:29')
, (29, 'Ea eveniet minima nesciunt sunt accusantium dignissimos eligendi sapiente.', 'zsenger@example.net', 'Rerum quaerat dolores cumque quia. Et enim blanditiis id dolore aliquid voluptatem. Consequatur est laboriosam impedit veritatis aut.', '1971-11-16 11:28:08', '1992-12-18 12:06:10')
, (30, 'Rerum necessitatibus quod sunt quasi.', 'jedidiah45@example.net', 'Explicabo sit et dolore dolorem. Numquam quidem voluptatem repellat excepturi non odit. Eos hic soluta non ea magni quasi voluptatem aut.', '1995-08-26 01:50:05', '2006-08-30 02:09:00')
, (31, 'Aut omnis veniam laborum quisquam sit.', 'martin13@example.com', 'Recusandae ipsa ut dolores doloribus. Alias quos autem nostrum dolores omnis consequatur nihil. Ut veritatis sunt consectetur voluptatibus. Deleniti ut dolorem est nesciunt tempore. Ea ipsum voluptatum autem sunt aut.', '1992-03-02 15:31:55', '1997-08-14 08:35:58')
, (32, 'Omnis voluptatem beatae neque aperiam.', 'berge.heloise@example.com', 'Consequatur sint et iure voluptatem et ea optio. Adipisci fugit tempore voluptatem et maiores nam sunt.', '2015-06-17 20:53:47', '1979-06-16 12:24:24')
, (33, 'Et doloremque nostrum voluptate fugit.', 'sallie.jacobs@example.net', 'Blanditiis omnis vero sequi consequatur reprehenderit suscipit et eum. Sit sit consectetur optio eius assumenda eos laborum. Labore et nihil autem earum dolorem nisi est. Dolorum rem beatae nulla ut ut sit neque.', '1977-04-22 16:51:45', '1976-03-31 08:14:42')
, (34, 'Reprehenderit neque aut doloribus quia.', 'brekke.meda@example.com', 'Quia quis deleniti quia nam non. Temporibus quis ratione quod aut.', '2020-08-03 01:35:06', '2008-07-20 04:50:20')
, (35, 'Recusandae inventore iste provident officia vitae aliquam.', 'georgianna62@example.com', 'Alias aut provident corrupti quia velit. Beatae excepturi recusandae nihil molestiae et minus. Harum voluptas sunt sunt placeat quia nesciunt pariatur eum.', '1988-07-19 03:36:57', '2010-11-30 03:21:57')
, (36, 'Ut perferendis quibusdam sed neque consequatur.', 'xbosco@example.org', 'Et repellendus et et ullam harum consequatur aut. Ipsum et quod cumque quibusdam. Excepturi id omnis numquam consequatur sed et.', '2006-07-08 07:39:46', '2000-09-07 17:28:51')
, (37, 'Corrupti laborum dolor recusandae quo repellat soluta.', 'bogisich.kendrick@example.net', 'Doloribus impedit qui quos. Dolorem ex aut fugiat aperiam. Culpa nihil dignissimos iste nam qui est et.', '2001-09-30 14:25:52', '1981-05-13 05:45:00')
, (38, 'Reiciendis sed tempore voluptas sint qui omnis perspiciatis.', 'amber40@example.net', 'Dignissimos veritatis aut sunt. Vitae non dolor repellendus est dolore necessitatibus. Aut ex quod suscipit voluptatem voluptatem reprehenderit.', '2004-12-01 00:25:50', '2011-02-27 02:14:17')
, (39, 'Soluta ut dolores tempora quis dolor eos.', 'simone.wisozk@example.com', 'At optio ipsum dolorum ut molestiae ullam. Expedita voluptatum ducimus et. Et molestiae accusantium qui natus rem.', '1971-09-09 20:24:01', '1973-02-17 00:07:30')
, (40, 'At reiciendis rerum laborum reprehenderit.', 'fae00@example.net', 'Velit et et autem ad. Aut impedit voluptatem autem perspiciatis possimus qui. Alias optio dolores voluptas numquam.', '2020-04-03 02:51:31', '1983-04-03 06:20:49')
, (41, 'Amet ipsam qui culpa et.', 'hara@example.net', 'Qui et laboriosam voluptatem. Culpa sed modi sit aperiam. Mollitia dolor excepturi repellendus deserunt omnis voluptatem.', '1975-02-28 23:27:43', '1997-02-20 05:30:13')
, (42, 'Sunt ducimus voluptas nihil vel.', 'carissa.bradtke@example.com', 'Aliquam ratione nobis ut nihil quibusdam quidem et. Doloremque cupiditate repellat dolorem in et consequatur eos. Ipsum a vitae enim non.', '2010-07-06 07:59:25', '2009-08-29 04:23:07')
, (43, 'Et est molestiae minima at impedit labore beatae.', 'loren.kilback@example.net', 'Sint et iure nisi iste tenetur autem sit. Distinctio ipsa tenetur adipisci dolores rem.', '1987-07-13 21:04:20', '1973-01-06 11:39:29')
, (44, 'Non modi sequi nobis ut illo.', 'wlynch@example.net', 'Possimus eum similique debitis recusandae fugiat dolor cumque. Laboriosam repellendus pariatur molestiae voluptatem temporibus sint sit. Vero nihil odio est quae corporis sapiente. Ut aliquid officia delectus vel atque magnam voluptatem. Voluptatem aliquid quae sunt fugit nobis quos non.', '1977-08-25 19:08:03', '1982-09-30 15:48:04')
, (45, 'Impedit ut doloribus dolore est vero.', 'qbednar@example.net', 'Eveniet molestiae iusto eos magni repudiandae nihil. Quia nihil et laborum odit. Voluptas est quidem voluptatem porro voluptatem in.', '1977-02-12 06:17:45', '1993-08-31 13:08:53')
, (46, 'Ut modi nam odio autem ab aut nihil.', 'federico.reilly@example.org', 'Suscipit omnis fugiat eligendi ut. Tempora consequatur omnis est est neque est ut. Aut est sed eius ea.', '1981-02-08 02:38:44', '1992-11-14 21:30:26')
, (47, 'Earum ab et voluptatem est.', 'destinee66@example.org', 'Voluptates nobis harum ut mollitia architecto. Minus voluptates debitis quia velit beatae. Nihil mollitia rerum cumque est. Sint a ipsam iusto quibusdam autem.', '2012-07-14 06:10:05', '1980-01-29 18:30:03')
, (48, 'Nostrum sequi aut deleniti iure autem ducimus.', 'wiza.lewis@example.com', 'Ipsum ad occaecati ullam unde nisi ullam qui. Veniam ipsum porro placeat quo asperiores. Placeat sint et veritatis quasi modi. In est debitis quis amet.', '1998-08-10 23:18:09', '2003-09-13 04:53:22')
, (49, 'Voluptatem omnis voluptatem vel et molestias labore impedit sint.', 'liana.jenkins@example.org', 'Cumque dolores aut dolorem quis ipsa deleniti. Sed porro dolor possimus eaque aut et culpa. Non ratione voluptatibus quo adipisci.', '2011-04-01 16:13:45', '2007-06-02 22:58:30')
, (50, 'Aliquid necessitatibus nihil aliquid ut est et.', 'rogelio.altenwerth@example.org', 'Doloremque doloremque architecto quas non sit molestiae doloremque. Fuga nobis soluta et consequatur ut vel aut voluptatem. Quia deleniti eveniet eius.', '1990-05-04 07:01:47', '2004-10-23 21:33:39')
, (51, 'Dolor incidunt quas vitae ullam et.', 'noemie51@example.net', 'Quis qui debitis eos aut. Cumque harum architecto quasi qui placeat quibusdam et. Et omnis autem harum. Eos quisquam voluptates magni aut sed at. Veritatis sint ut eaque magni aut repellendus.', '1996-05-16 04:46:13', '2012-08-19 20:18:07')
, (52, 'Quia laborum dolores id iusto et rerum.', 'talia.thiel@example.org', 'Aut distinctio quam nihil dolores enim non autem soluta. Et sed dolor quas voluptatem et.', '2020-02-27 08:14:40', '1989-10-12 09:20:28')
, (53, 'Ea itaque enim delectus vitae provident.', 'sandy.kuvalis@example.com', 'Velit accusantium iste atque eius voluptatem. Quis ad ea accusamus harum nostrum neque quasi. Dolorem illum hic optio iusto tempore sit. Vel labore natus nemo enim aut laborum neque.', '1998-01-11 22:29:51', '2010-04-23 19:48:05')
, (54, 'Voluptas perferendis voluptatum nesciunt ut rerum odit temporibus.', 'joshua.kuvalis@example.net', 'Et quia cupiditate molestiae quam. Consequuntur odio cumque voluptatum sequi aperiam. Quia repudiandae sit eos. Maxime ullam non error nam consequuntur.', '2010-08-26 02:15:17', '1979-08-05 00:13:11')
, (55, 'Ut a aut sequi nemo qui iusto velit.', 'elouise.luettgen@example.net', 'Aliquid dolor qui aliquam mollitia id doloremque. Sapiente et ea accusantium quidem mollitia quis. Alias soluta labore vel quae sint. Nulla expedita praesentium maiores dignissimos tenetur quae.', '1985-10-15 11:36:01', '2020-03-15 23:43:41')
, (56, 'Eum quisquam ut possimus quae qui pariatur quisquam.', 'brekke.alden@example.net', 'Porro nulla placeat nobis sed. Sed dicta ducimus dolorum ab sint autem ea. Et ab inventore reiciendis rerum laudantium velit.', '1974-06-13 10:51:16', '1980-01-06 03:52:21')
, (57, 'Enim officia sed est saepe.', 'pacocha.dorothea@example.org', 'Voluptatem autem ut delectus qui non sunt qui. Deserunt exercitationem cumque pariatur aliquid non. Soluta consequatur voluptas nemo omnis et libero incidunt quo. Sint quia ipsa inventore aut ut repellendus.', '1997-11-29 02:00:03', '2016-12-27 07:53:04')
, (58, 'Numquam veritatis deleniti ut vero assumenda eum eveniet libero.', 'morris79@example.net', 'Voluptatem nam blanditiis omnis sit possimus. Magnam consequatur nostrum sequi consequuntur. Deleniti suscipit eum voluptatem tenetur laboriosam velit ut.', '1975-12-29 20:02:40', '2001-09-12 19:00:39')
, (59, 'Modi nulla laudantium sed aliquid aut.', 'darron.shields@example.net', 'A exercitationem iure dolorem. Consequatur et sunt voluptate laudantium. Quaerat quisquam repellendus ea repudiandae dolorem aut. Et doloribus vitae voluptatem molestias.', '2015-09-22 02:04:23', '2016-08-09 02:18:27')
, (60, 'Blanditiis eum a iure ipsa asperiores error.', 'berta96@example.com', 'Magni provident unde aut excepturi aut veniam quia. Ea quasi adipisci consectetur ut vel atque iste ea. Ut ut deleniti doloremque qui.', '2018-09-25 01:30:16', '2015-11-25 14:36:15')
, (61, 'Et quidem illo sapiente dicta optio pariatur.', 'cjohnson@example.com', 'Quia aut dolore molestiae incidunt autem consequatur quas. Sit necessitatibus quaerat et. Illum iste sit non dolorem consequatur labore impedit quisquam. Fuga et magni rerum enim sint id cupiditate.', '1992-09-16 09:19:06', '1984-01-15 22:39:56')
, (62, 'Accusamus sed omnis aut quaerat.', 'trice@example.org', 'Aspernatur ullam cum exercitationem ea temporibus. Culpa odit ut fugiat vel tempore et est mollitia. Iure nesciunt id sed quia recusandae quis quod fuga.', '2018-09-27 19:30:36', '1971-06-05 04:01:51')
, (63, 'Aperiam id aspernatur architecto quia sed libero cum.', 'hilll.arvilla@example.net', 'Ipsam aperiam aliquid itaque aperiam neque impedit. Vel molestias perspiciatis quam tempore aut. Illo harum aut sit nihil nisi repudiandae soluta tempore. Tempore repellendus ipsa necessitatibus veritatis.', '2001-03-07 06:15:44', '2010-07-06 02:26:27')
, (64, 'Blanditiis dolorem illo omnis et at.', 'hackett.maurine@example.org', 'Quasi sunt dolore magnam exercitationem alias id iste. Et aut perferendis nihil quia et at. Et quis odio iure.', '1986-05-10 14:21:03', '2004-05-24 23:18:35')
, (65, 'Culpa in adipisci asperiores molestias tempore reprehenderit ex.', 'larson.wilbert@example.com', 'Adipisci non dicta recusandae excepturi fugiat et. Non rerum fuga voluptatibus. Cupiditate aut sed nihil ea rem quia. Laborum officiis qui quis.', '1992-04-30 18:06:37', '1972-06-19 15:37:14')
, (66, 'Facere dolorem iusto reiciendis recusandae aut mollitia sit.', 'reyes58@example.org', 'Iste soluta tempore dolores dolores et. Tenetur optio provident qui amet. Vel et sint recusandae voluptas non consequuntur. Consequatur temporibus numquam et animi.', '2009-08-26 13:16:39', '2005-05-18 03:13:27')
, (67, 'Dolores minus consequatur repellendus autem eum.', 'steuber.mary@example.net', 'Veniam inventore voluptatem ea occaecati et explicabo sed. Ipsam placeat tenetur iure rerum voluptas ut. Quis voluptatem deleniti eum vel voluptatum vero.', '2020-07-29 09:22:55', '1989-11-14 23:18:06')
, (68, 'Quos eos molestias aut dolores porro.', 'mitchell45@example.com', 'Mollitia enim quisquam omnis eveniet vitae fuga. Rerum architecto pariatur qui deleniti voluptatem omnis. Non ut vero quae facilis ut alias.', '1986-08-13 16:17:51', '1975-04-15 03:21:35')
, (69, 'Est adipisci sequi eligendi officiis.', 'gkshlerin@example.com', 'Esse deleniti incidunt fugiat tempore et nam. Ratione nobis vitae deserunt et. Nesciunt qui exercitationem architecto quod facere assumenda. Voluptas itaque ut qui quam impedit aut hic.', '1973-09-01 16:19:56', '2005-02-05 22:10:06')
, (70, 'Unde enim quos tenetur tenetur rerum.', 'bergstrom.katlynn@example.com', 'Libero doloribus quis est qui molestiae. Pariatur est eveniet quo cum et quis qui repudiandae. Tempora reiciendis explicabo et et cum.', '2006-03-14 19:22:37', '1991-10-14 09:52:42')
, (71, 'Ut voluptates molestias quia doloribus corrupti.', 'roselyn62@example.org', 'Esse distinctio ipsa vitae ut velit libero. Totam ex dicta rerum porro distinctio. Facere quo consequatur nobis animi quibusdam enim commodi. Nihil dolor adipisci iste sequi nemo.', '1986-10-31 01:37:42', '2019-06-08 16:19:56')
, (72, 'Consequuntur quo ea commodi ducimus.', 'ralph.kirlin@example.org', 'Doloremque reiciendis laudantium dolorem illo. Dolorem qui officiis unde et odit.', '1975-05-19 14:08:17', '1984-01-16 03:45:16')
, (73, 'Occaecati temporibus vel quasi et.', 'veum.cortney@example.com', 'Itaque alias ratione consequatur vel amet quidem. Id nisi quia eos omnis expedita ducimus illo. Aliquid et praesentium id consequatur vero et eius.', '1984-08-23 15:06:04', '1985-09-18 10:01:58')
, (74, 'Ut a delectus impedit.', 'noel05@example.net', 'Voluptatem dignissimos sequi iure omnis et sed et eligendi. Sequi dicta in tenetur eos. Asperiores et incidunt quos recusandae harum. Quia consequuntur nihil quia officia nobis nihil est.', '1994-03-01 02:37:45', '2011-05-17 21:23:08')
, (75, 'Rerum ad magnam distinctio qui corrupti enim occaecati sunt.', 'etillman@example.org', 'Ratione sit dolorum illo officiis consequatur qui. Sapiente ut tenetur enim.', '1998-04-25 02:06:12', '1970-12-06 18:12:03')
, (76, 'Eum ut repudiandae eum ut.', 'kwilkinson@example.org', 'Ut numquam ipsum perferendis molestiae. Ipsa exercitationem voluptas voluptates cum. In molestiae et nulla quidem sit et voluptas perferendis. Atque autem unde accusamus fugiat.', '1979-05-05 02:21:27', '1992-10-07 11:20:29')
, (77, 'Excepturi veritatis id velit eveniet a non eligendi.', 'philip98@example.org', 'Sapiente molestiae itaque rerum repellendus esse. Numquam expedita omnis placeat ut. Quisquam delectus labore maxime. Consequatur est ut aliquid consequatur inventore cupiditate.', '1979-07-01 21:54:13', '2000-07-29 14:12:13')
, (78, 'Eum non voluptatum quod nesciunt deserunt sit ratione.', 'qkohler@example.org', 'Quo porro voluptate tempore qui eum veritatis dolor. Qui et minima soluta doloremque magni. Sunt quas expedita hic.', '1970-02-19 11:51:16', '1970-07-26 08:08:47')
, (79, 'Quia qui ea non rerum quod harum qui.', 'yortiz@example.org', 'Nobis dolorem saepe quia. Iste alias dolorem voluptates. Atque sit ab sit explicabo provident ipsam. Voluptates perferendis sit quod iusto. Eaque molestias occaecati suscipit sit laboriosam accusantium eveniet.', '2012-11-03 10:53:01', '1999-11-18 14:10:15')
, (80, 'Earum et velit blanditiis saepe porro.', 'dylan45@example.net', 'Quia magnam officiis omnis ut veniam. Iusto aliquam sequi animi corporis voluptates sit et. Laudantium provident quisquam laudantium natus nobis dignissimos aut. Consequuntur ipsam molestiae dolorem velit.', '2015-02-02 07:49:49', '1995-06-21 21:31:36')
, (81, 'Consequatur enim in et dolor aut eveniet quae.', 'bergstrom.karlee@example.net', 'Maxime quisquam ut non eaque iure. Minima aspernatur deleniti ratione id magni temporibus mollitia. Vitae rerum laborum illum voluptatibus.', '1994-12-27 13:25:47', '1990-04-19 21:39:28')
, (82, 'Qui iusto tempora incidunt animi maiores.', 'witting.laverne@example.net', 'Sint non consequatur dolores autem unde eligendi. Exercitationem saepe qui nesciunt consequatur aut voluptates similique. Rerum maiores quidem esse sunt aut qui.', '1972-02-25 19:03:00', '2010-09-02 14:56:37')
, (83, 'Consequuntur eligendi nam beatae accusamus.', 'nrutherford@example.org', 'Voluptatem veniam eos est. Quasi et nostrum vero sint soluta impedit quis. Et optio vitae maiores aut. Culpa dicta ratione minus praesentium magni.', '1995-10-12 15:45:00', '1975-07-31 03:31:41')
, (84, 'Nihil laborum nam consectetur voluptatibus unde.', 'qkiehn@example.org', 'Voluptas tempora dolor nostrum dolor quod porro. Quia qui ad sapiente. Non consequatur culpa quasi velit quasi. Cum molestias delectus sit natus.', '1972-02-28 17:16:27', '1977-01-13 04:31:28')
, (85, 'Aliquam itaque velit perspiciatis nobis.', 'filomena30@example.net', 'Necessitatibus ad nostrum doloribus molestiae. Ut eum aperiam nostrum blanditiis impedit facilis. Non et excepturi itaque velit qui. Ea exercitationem distinctio repellendus quibusdam enim modi et. Quo praesentium impedit pariatur iusto impedit.', '1985-07-14 07:20:30', '1997-04-07 19:54:44')
, (86, 'Velit odit quia sequi illo cumque suscipit.', 'natalia23@example.com', 'Velit ex veritatis quidem impedit excepturi fuga iste quos. Non ea quasi libero dolores occaecati. Sequi consequatur ipsa quaerat et.', '1998-07-10 20:30:56', '2005-03-26 13:29:07')
, (87, 'Et quibusdam incidunt quibusdam sit et.', 'isabel97@example.com', 'Deserunt vero deserunt vero sed consequatur repudiandae. Quos dignissimos accusantium omnis nihil nobis voluptatem fugiat sit. Et laboriosam voluptate perspiciatis vel rerum rerum tenetur est. Voluptatibus vel qui quaerat.', '1990-09-17 23:59:12', '1991-06-05 18:57:13')
, (88, 'Maiores ut recusandae et quis fuga quidem.', 'fmann@example.net', 'Voluptatem illo at excepturi eligendi repellat fuga. Rerum molestias sed modi.', '1977-06-15 07:27:21', '1987-04-12 01:50:31')
, (89, 'Eveniet aliquid ea delectus excepturi sapiente ea.', 'tara.lesch@example.net', 'Sit magnam harum qui dolorem. Quaerat aut sed nulla beatae quia omnis in. Libero quis quas mollitia cumque officiis consequatur consequatur. Molestiae facilis vel animi eos. At dolores qui architecto reprehenderit.', '1983-01-01 14:20:27', '1997-06-21 14:03:54')
, (90, 'Maiores quia ea non dolorum quibusdam vel.', 'zpfannerstill@example.org', 'Aut sed quisquam atque nihil magni in sapiente. Odio dolorem iure veniam omnis beatae magni. Dicta ducimus facilis qui atque magni dolore. Culpa rerum aut sint dolorem rerum ut.', '2018-06-06 04:41:13', '2018-10-15 08:58:39')
, (91, 'Laborum aut pariatur aperiam qui ut.', 'bennie.ryan@example.net', 'Commodi molestiae explicabo necessitatibus quis. Fugiat voluptatem blanditiis et vitae eum. Nostrum necessitatibus in quae quod. Repudiandae necessitatibus modi quia aut quia laudantium.', '1992-09-27 15:44:15', '1994-12-20 07:41:10')
, (92, 'Dolore dolor non unde reprehenderit nam culpa.', 'eemmerich@example.com', 'Nobis eos quidem eum expedita fugit dolorem. Ratione qui ut est. Enim pariatur voluptates voluptatem fugiat iste corporis. Libero veritatis sit a recusandae rerum et.', '2019-08-28 18:53:30', '1976-04-13 06:29:53')
, (93, 'Quia id dolores blanditiis hic quis aspernatur quos.', 'lambert00@example.org', 'Dolores nemo sint sunt iste. Asperiores qui dolorum hic voluptas quisquam doloremque eveniet excepturi. Error molestiae est commodi rerum illum.', '1970-07-25 20:53:12', '2016-12-17 17:43:14')
, (94, 'Sequi consequatur et quae sit.', 'hilpert.stephania@example.com', 'Est dicta qui fugit id. Libero nihil provident sequi voluptatum quia vel voluptatem. Est et ducimus unde consequatur fugit iusto minus sunt. Ipsam exercitationem enim neque est voluptatem. Natus quae consequatur inventore.', '2012-05-10 17:01:27', '1997-02-06 10:38:40')
, (95, 'Enim quos ducimus libero ipsum qui eius veritatis tenetur.', 'leopoldo86@example.net', 'Nam quae optio nisi amet sint dignissimos illo. Est illo repellendus quos culpa et voluptatem. Accusantium deleniti aut iure eligendi est. Sed dignissimos aliquid occaecati eaque ut sed in sint.', '1985-06-05 15:02:14', '1985-10-14 23:58:17')
, (96, 'Et similique dolor laborum nihil.', 'lela.stokes@example.net', 'Voluptas dicta ad id neque praesentium quo iure. Est et repellat architecto illum vitae. Qui illum earum hic possimus doloremque placeat error. Unde officiis unde dolorem ut molestiae eos.', '1995-07-24 11:36:26', '2000-06-16 16:51:46')
, (97, 'Et deleniti totam dicta est nemo.', 'hettie.tillman@example.com', 'Suscipit itaque iste sint quam ut libero. Dicta dolorum adipisci sint illo. Fugit ad nihil et sunt est earum. Et qui sunt hic sed nihil dolor aliquam.', '1996-05-27 15:19:00', '1970-10-13 03:23:18')
, (98, 'Laudantium ab totam repellat rerum vero dolore.', 'schinner.florence@example.org', 'Laborum vel corporis in quia veniam placeat suscipit. Explicabo odit quaerat fugiat praesentium distinctio nemo et id. Esse facere ad consequuntur dolores cupiditate.', '2008-12-16 15:12:00', '2006-06-04 23:53:54')
, (99, 'Eos earum illum explicabo.', 'hal.mitchell@example.net', 'Nesciunt est ullam non eos fugit facilis. Eum praesentium et quae facere recusandae assumenda et doloribus.', '2013-05-07 16:14:10', '2013-03-04 18:54:42')
, (100, 'Eum inventore quam tenetur necessitatibus.', 'vschamberger@example.org', 'Vel doloremque dignissimos dolores asperiores ea dolor. Consequuntur consectetur eum natus distinctio quis ducimus nostrum. Saepe autem possimus saepe qui sed quae rerum. Molestiae est numquam autem adipisci.', '1980-10-13 21:24:12', '1973-04-12 11:30:00');
*/